streams:
  hall-camera: rtsp://admin:password@192.168.1.123/cam/realmonitor?channel=1&subtype=0
  streams:
  dahua:
    - rtsp://admin:password@192.168.1.123/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
    - ffmpeg:rtsp://admin:password@192.168.1.123/cam/realmonitor?channel=1&subtype=0#audio=opus
api:
  listen: "10.0.0.9:0000" # localhost

rtsp:
  listen: "10.0.0.5:0000" # localhost

webrtc:
  listen: ":0000" # external TCP/UDP port
